version: '3.7'
services:
    php:
        container_name: app_pactual
        build:
            context: .
            dockerfile: .docker/apache/dockerfile
        image: 'ubuntu-laravel'
        ports:
            - 80:80
        volumes:
            - .:/var/www/html
        networks:
            - mysql-compose-network

    mysqlsrv:
      container_name: app_pactual_mysql
      image: mysql:5.7
      command: --explicit_defaults_for_timestamp
      environment:
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_DATABASE: "pactual"
      ports:
        - "3306:3306"
      volumes:
        - .:/var/lib/sql
      networks:
        - mysql-compose-network


networks: 
  mysql-compose-network:
    driver: bridge